/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Jenkins_feature_branch;

public class Library {
    public boolean someLibraryMethod() {

        System.out.println("This is feature 3");
        System.out.println("Hello World");

        return true;
    }
}
